In [1]:
import tensorflow as tf
from tensorflow.keras import layers, Model, Input, initializers
from tensorflow import keras
import tensorflow.keras.backend as K
import keras_rs
import keras_tuner as kt

import numpy as np

In [4]:
import urllib.request

url = 'https://public-dataset-letor.s3.eu-central-1.amazonaws.com/test.txt?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOb%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDGV1LWNlbnRyYWwtMSJHMEUCID1WOR39Y7jSysbukHGpkXnozXanF%2FrsHd3c0%2FZzHfPYAiEA9yyDtHPbvIiTnEVqbNdy2vvEscmR6eacR7RD9LEWQGIquQMILxADGgw4NTI4NTc3MjMzMzciDFaKuuPPeM6JtCD2ACqWA%2BFqrU5kx%2FeDNGthTxYmKD2ZfGB0HwrwxW3dtSoz1QET8FmrguvsyfdB7Qohge7G4czoVAjRioxb70PJQFvT%2Fo7gzmvY%2FZI1BYxz1%2Fit7%2Bq4ovkB9NQG3qrSCvMyrxkYLvCiuchZRxoEP0Ty1hME3n8SNiEGlaHf%2BwKni%2FOUvCJNaUblQfKiEUEcBQtccw5cz1VGjivr%2BVhlVMrguJRA15xWF55h5MmYyJ5vO%2BKgFKndF%2BdKc7nOu1lty6Z%2BaGMnr4ZfwQ%2Fg3OgSmBtYodbZYd5iGyyAidF3%2B6k9sPJgN4a9enp6%2FvBhPrUmQy6qL6m17jZ5XnBiA5tfbandOZHC1qbTkqTnYVzDBie48GCCbNoRWAbTtHT5EkQHOpNALWYupyYFOZNSZgowa4bhxJNDjE8NhBPqY7pXanvP3ePWVzBJroJVu3xNoaIfKk69SOEOzrvVLPrv7Cg9TkQwYuKisS4%2FzYVoPP2GfCX%2F%2BSXExDxK8b%2BsNvD1o%2FI0%2FTUUV1WNSZshS5qZveeLl25T%2FtmbJR50mYzsuCkw3e3xxAY63gLQSGVbuKkwPhgTu%2F30kaX8IPhFjz1cNy1%2FuuOSS2Z9hWaBWxcZF3Kai%2BpzAXj9T%2BSE20EoaA6fn0GRX1c%2FAq7nYoaMaAy33tb0IDoe9e5AMl5NN27I6t9GDoXv%2F%2FOWRi%2F7ZNQOeMbLeV1uqc2Mzga510b5kYWU0b0i4fCt2lYewsOtoqlKYdGeFjlaeWwA4VJZHGDFpqCJo%2FnCGiyNg7kkwP2ux1c8km2oL84QK%2BKyfVI9NpXHd8JYc9RTJ9vxmDizB3yX%2FCYH%2BC7oGFhXUHhPYVlGuZn1O5TwX0E8XXuUNsAc9p0xbMgC1DdJtQZEXKyb7ESIEsoMbV%2FsxdiOciJblQZODtu0egsQv0yBLBJMQh27qDs5WeUTMHQGOjmeovpl%2Br0afnTfyQGgz9xkOd8zl2sRKQXe8oqHg6kbjrBQp9AEYPMdI1vskl%2Fr0a%2F3As2u1vwRiO%2FToxFCC%2Btn8g%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIA4NESIDHE52JVHYDB%2F20250813%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20250813T141122Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=f074a3041c7f3cacf1f3fafd4b1e667005af6210717994b0a05dc49d37a34049'  # Replace with your zip file URL
output_path = 'file.zip'  # The file name you want to save as

urllib.request.urlretrieve(url, output_path)
print("Download complete!")

Download complete!


In [6]:
import urllib.request
import zipfile

output_path = 'MSLR-WEB10K.zip'  # The file name you want to save as
# # Step 1: Download the zip file
# url = 'https://example.com/path/to/your/file.zip'  # Replace with actual URL
# output_path = 'file.zip'
# urllib.request.urlretrieve(url, output_path)

# Step 2: Extract the zip file
with zipfile.ZipFile(output_path, 'r') as zip_ref:
    zip_ref.extractall('extracted_folder')

print("Download and extraction finished.")

Download and extraction finished.


## Main idea

Even though we most often care about only k first documents in the ranking it doesn't mean that we should learn relative relevance between documents at the tail of the labeled ranked lists

TODO:
- check whether masking for padded is being applied. Try ragged tensors.
- try bigger max_retires
- why get_best model having issues with resetting the weights ??

## Hyper model

In [54]:
class SelfAttentionBlock(layers.Layer):
    def __init__(self, emb_dim, hp, name_prefix=''):
        super().__init__(name=name_prefix)
        
        attention_heads = hp.Int('attention_heads', min_value=1, max_value=4, step=1)
        attention_dropout_rate = hp.Float('attention_dropout_rate', 0.1, 0.4, step=0.1)
        
        self.attn = layers.MultiHeadAttention(
            num_heads=attention_heads,
            key_dim=emb_dim,
            dropout=attention_dropout_rate,
            name=f'{name_prefix}_attn'
        )
        self.add_layer = layers.Add(name=f'{name_prefix}_residual')
        self.norm = layers.LayerNormalization(name=f'{name_prefix}_norm')

    # def call(self, x, mask=None):
    def call(self, x, mask=None):
        attn_output = self.attn(x, x, attention_mask = mask)
        # assert mask is not None , "Mask should be passed"
        # print(f"Shape of the attn_output {attn_output.shape}")
        
        x = self.add_layer([x, attn_output])
        x = self.norm(x)
        return x
    
class RankingModel(keras.Model):
    def __init__(self, num_users, num_items, embedding_dim, hp):
        super().__init__()
        
        dense_units = hp.Int('dense_units', min_value=16, max_value=128, step=16)
        dense_units_2 = hp.Int('dense_units_2', min_value=16, max_value=128, step=16)
        dropout_rate = hp.Float('dropout_rate', 0.1, 0.4, step=0.1)
        dropout_rate_2 = hp.Float('dropout_rate_2', 0.1, 0.4, step=0.1)
    
        # self.user_embedding = layers.Embedding(num_users, embedding_dim)
        # self.item_embedding = layers.Embedding(num_items, embedding_dim, name = "items_embeddings")
        
        self.inputs = layers.Input(shape=(None,), ragged=False, dtype=tf.int32)
        self.masked = layers.Masking(mask_value=0.0)
        #Self-attention block (respects masks automatically if using Functional API)
        self.attn_self = SelfAttentionBlock(embedding_dim, hp, name_prefix='self_attenction_block_1')
        
        self.dense1 = layers.Dense(dense_units, activation='relu', name = "dense1")
        self.dropout1 = layers.Dropout(dropout_rate)
        self.dense2 = layers.Dense(dense_units_2, activation='relu')
        self.dropout2 = layers.Dropout(dropout_rate_2)
        self.score_layer = layers.Dense(1)  # output predicted score per item

    def call(self, inputs):
        # inputs assumed to be dict with user_id and item_id tensors of shape [batch_size, list_size]
        # user_id = inputs['user_id']  # shape [batch_size, 1] or [batch_size]
        doc_features = inputs['doc_features']  # shape: [batch_size, list_size, num_doc_features]
        # LIST_SIZE = tf.shape(doc_features)[-1]  # number of items per query/list
        
        masked = self.masked(doc_features) 
        # print(f"Type of the masked {type(masked)}")
        # tf.print('Shape of the mask', masked.shape)
        mask_tensor = masked._keras_mask
        mask_expanded = mask_tensor[:, tf.newaxis, :]  # broadcast from (B, S) to (B, 1, S). For not self-attention  T!=S we need another shape
        
        # print(f"Shape of the doc_features {doc_features.shape}")
        # print(f"Shape of the mask {mask_tensor.shape}")
        # print(f"Shape of the mask_expanded {mask_expanded.shape}")
        
        x = self.attn_self(masked , mask_expanded)
        
        # print(f"Shape of the atten_block_out {x.shape}")
        # print(f"Type of the x {type(x)}")
        # add_mask = x._keras_mask
        # print(f"Shape of the add_mask {add_mask.shape}")
        # raise ValueError("Stop")
        
        x = self.dense1(x)  # [batch_size, list_size, 64]
        x = self.dropout2(x)
        x = self.dense2(x)  # [batch_size, list_size, 32]
        scores = self.score_layer(x)  # [batch_size, list_size, 1]
        scores = tf.squeeze(scores, axis=-1)  # [batch_size, list_size]

        return scores

In [55]:

class RankingHyperModel(kt.HyperModel):
    def __init__(self, num_users, num_items, embedding_dim, loss_fn):
        self.num_users = num_users
        self.num_items = num_items
        self.embedding_dim = embedding_dim
        self.loss_fn = loss_fn

    def build(self, hp):
        dense_units = hp.Int('dense_units', min_value=16, max_value=128, step=16)
        dense_units_2 = hp.Int('dense_units_2', min_value=16, max_value=128, step=16)

        model = RankingModel(
            num_users=self.num_users,
            num_items=self.num_items,
            embedding_dim=self.embedding_dim,
            hp=hp
        )

        model.compile(
            optimizer=keras.optimizers.Adagrad(
                learning_rate=hp.Choice('learning_rate', values=[0.01, 0.05, 0.1])
            ),
            loss=self.loss_fn,
            metrics=[]  # add your metrics here
        )
        return model


## Custom loss

In [56]:


# def build_hypermodel_ltp(hp):

# Example constants
NUM_USERS = 1000
NUM_ITEMS = 500
EMBEDDING_DIM = 32

# player_emb_dim = hp.Choice('player_emb_dim', [8, 16, 32])

# learning_rate = hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])
# dropout_rate = hp.Float('dropout_rate', 0.1, 0.4, step=0.1)

# Custom Ranking Model: embedding users and items, and predicting scores per list item

# Use ListMLE loss from TensorFlow Ranking (listwise loss)
# loss_fn = tfr.keras.losses.ListMLELoss()

def custom_loss(y_true, y_pred, debug = False):
    if debug:
        tf.print("y_true:\n", y_true)
        tf.print("y_pred:\n", y_pred)
    
    def transform_sequence(inputs):
        y_true_seq, y_pred_seq = inputs
        # seq shape: [seq_len, feature_dim] for a single batch element
        # Implement your transformation here for one sequence

        list_dim = tf.shape(y_true_seq)[0]
        indexes = tf.range(list_dim)
        if debug:
            tf.print("indexes:", indexes)

        # Create meshgrid i and j indices over list_dim
        i, j = tf.meshgrid(indexes, indexes)  # shape (list_dim, list_dim)

        # Mask upper triangular matrix indices where i < j
        upper_tri_mask = tf.linalg.band_part(tf.ones((list_dim, list_dim), dtype=tf.bool), 0, -1) & \
                            ~tf.linalg.band_part(tf.ones((list_dim, list_dim), dtype=tf.bool), 0, 0)
        
        if debug:
            tf.print("upper_tri_mask\n", upper_tri_mask)
        
        i_idx_of_pair = tf.boolean_mask(i, upper_tri_mask)  # shape (num_pairs,)
        j_idx_of_pair = tf.boolean_mask(j, upper_tri_mask)  # shape (num_pairs,)
        
        num_pairs = tf.shape(i_idx_of_pair)[-1]
        
        if debug:
            tf.print("i_idx_of_pair\n", i_idx_of_pair, summarize=-1)
            tf.print("j_idx_of_pair\n", j_idx_of_pair, summarize=-1)
            # tf.print("i_idx_of_pair\n", tf.shape(i_idx_of_pair))
            tf.print("i_idx_of_pair.shape\n", tf.shape(i_idx_of_pair), summarize=-1)
            tf.print("y_true_seq.shape\n", tf.shape(y_true_seq), summarize=-1)
        
        true_i = tf.gather(y_true_seq, i_idx_of_pair, axis=0, batch_dims=0)  # (batch, num_pairs, emb_dim)
        true_j = tf.gather(y_true_seq, j_idx_of_pair, axis=0, batch_dims=0)  # (batch, num_pairs, emb_dim)
        
        if debug:
            tf.print("true_i\n", true_i, summarize=-1)
            tf.print("true_j\n", true_j, summarize=-1)
        
        pred_i = tf.gather(y_pred_seq, i_idx_of_pair, axis=0, batch_dims=0)  # (batch, num_pairs, emb_dim)
        pred_j = tf.gather(y_pred_seq, j_idx_of_pair, axis=0, batch_dims=0)  # (batch, num_pairs, emb_dim)
        
        if debug:
            tf.print("pred_i\n", pred_i, summarize=-1)
            tf.print("pred_j\n", pred_j, summarize=-1)
        
        # pair_emb = tf.concat([emb_i, emb_j], axis=-1)  # (batch, num_pairs, 2*emb_dim)
        # tf.print("pair_emb:", tf.shape(pair_emb))
        true_dist = true_j - true_i
        pred_dist = pred_j - pred_i
        if debug:
            tf.print("true_dist\n", true_dist, summarize=-1)
            tf.print("pred_dist\n", pred_dist, summarize=-1)
        
        dist_diffs = tf.abs(true_dist - pred_dist)
        if debug:
            tf.print("dist_diffs\n", dist_diffs, summarize=-1)
        
        
        # weigts
        decreasing = tf.linspace(1.0, 0.0, num_pairs)
        probabilities = decreasing / tf.reduce_sum(decreasing)
        if debug:
            tf.print("probabilities\n", probabilities , summarize=-1)
        weight_i = tf.gather(probabilities, i_idx_of_pair, axis=0, batch_dims=0)  # (batch, num_pairs, emb_dim)
        weight_j = tf.gather(probabilities, j_idx_of_pair, axis=0, batch_dims=0)  # (batch, num_pairs, emb_dim)
        comb_avg_prob = (weight_i + weight_j) / 2.0
        if debug:
            tf.print("comb_avg_prob\n", comb_avg_prob , summarize=-1)
        
        total_discrepancy = tf.reduce_sum(dist_diffs * comb_avg_prob)
        if debug:
            tf.print("total_discrepancy\n", total_discrepancy , summarize=-1)
        
        return total_discrepancy
    
    
    elems = (y_true, y_pred)
    transformed = tf.vectorized_map(transform_sequence, elems)
    
    # return K.mean(K.abs(K.square(y_pred) - K.square(y_true)), axis=-1) / gt_combinations['a']
    return transformed

hypermodel = RankingHyperModel(NUM_USERS, NUM_ITEMS, EMBEDDING_DIM, custom_loss)
# Compile with a suitable optimizer

# hypermodel.compile(optimizer=tf.keras.optimizers.Adagrad(learning_rate=0.1), loss=custom_loss)

# return hypermodel



## Dummmy data

In [90]:
# Dummy example data:


batch_size = 3

# user ids shape: [batch_size]
user_ids = np.array([1, 5, 7])

# item ids shape: [batch_size, list_size]
item_ids = np.array([
    [10, 20, 30, 40, 50],
    [5, 10, 15, 25, 35],
    [1, 2, 3, 4, 5]
])

# true relevance labels shape: [batch_size, list_size]
# Higher score means more relevant
y_true = np.array([
    [3.0, 2.0, 1.0, 0.0, 0.0],
    [1.0, 4.0, 2.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 5.0]
])

# Construct input dictionary for model.fit
train_x = {
    'user_id': user_ids,
    'item_id': item_ids
}
print(user_ids.shape)
print(item_ids.shape)


# Train the model with listwise inputs and listwise loss
# model.fit(train_x, y_true, epochs=50, batch_size=batch_size)

(3,)
(3, 5)


In [ ]:
# def group_by_query_id(X_docs, y_docs, qids_docs, debug=False):
#     # Example data
#     qids = qids_docs # np.array([1, 1, 2, 2, 2, 3])   # query IDs
#     X = X_docs #np.arange(len(qids) * 4).reshape(len(qids), 4)  # (num_pairs, num_features)
    
#     if debug:
#         print("Original shape:\n", X)  # (6, 4)
#         print("Original shape:", X.shape)  # (6, 4)

#     # 1. Find unique query IDs and mapping from doc index to query index
#     unique_qids, inverse_indices = np.unique(qids, return_inverse=True)
#     num_unique_queries = len(unique_qids)
#     num_features = X.shape[1]

#     # 2. Find max docs per query
#     docs_per_query = np.bincount(inverse_indices)
#     max_docs = docs_per_query.max()

#     # 3. Allocate padded output
#     item_ids_padded = np.zeros((num_unique_queries, max_docs, num_features), dtype=X.dtype)
#     y_grouped = np.zeros((num_unique_queries, max_docs), dtype=y.dtype)

#     # 4. Fill the padded array
#     # for i, qid in enumerate(unique_qids):
#     #     mask = (qids == qid)
#     #     docs = X[mask]
#     #     padded[i, :docs.shape[0], :] = docs
#     #     labels = y_docs[mask]
#     #     y_grouped[i] = labels
        
#     for q in range(num_unique_queries):
#         mask = inverse_indices == q
#         docs = X[mask]
#         labels = y_docs[mask]
#         item_ids_padded[q, :docs.shape[0], :] = docs
#         y_grouped[q, :labels.shape[0]] = labels

#     # print("Grouped & padded shape:", padded.shape)
#     # padded[i] now has all docs for query i (padded with zeros where needed)
#     # print("Grouped & padded:\n", padded)
#     return item_ids_padded, y_grouped, np.array(range(num_unique_queries))

In [206]:
quids = np.array([1, 1, 2, 2, 2, 3])  
y_labels = np.array([3.0, 2.0, 1.0, 0.0, 2.0, 4.0])   # labels, shape (num_pairs,)
x_train = np.arange(len(qids) * 4).reshape(len(qids), 4)  # shape (len_quids, doc_features).  doc_features= 4 here
groupped_padded, labels_grouped = group_by_query_id(x_train ,y_labels, quids)
print(groupped_padded.shape)
print(labels_grouped)

ValueError: too many values to unpack (expected 2)

## Snadbox code

In [39]:
if False:
    ground_truth_sorted = ["a", "b", "c", "d"]
    deduced_relevances = { label: rel for label, rel in zip(ground_truth_sorted, range(len(ground_truth_sorted) -1, -1, -1)) }
    print(deduced_relevances)
    ground_truth_unsorted = ["c", "b", "d", "a"]
    ground_truth_rels = [deduced_relevances[el] for el in ground_truth_unsorted]
    print(f"ground_truth_rels: {ground_truth_rels}") # [1, 2, 0, 3]

    predicted = [ 2.2, 1.8, 0.5, 3.5] # intentional error is done as for descenting order we should had [1.8, 2.2, 0.5, 3.5]
    print(f"predicted: {predicted} instead of correct: {[1.8, 2.2, 0.5, 3.5]}")

    # then we should take scores and use them to induce ordering ( descending) and apply this ordering to the ground_truth_rels(ie y_true)

                    # order = np.argsort(predicted)[::-1]
                    # print(f"Order for predicted` with argsort: {order}")
                    # dcg_score = dcg(np.take(ground_truth_rels, order) )

                    # print(f"DCG: {dcg_score}")

                    # order_ideal = np.argsort(ground_truth_rels)[::-1]
                    # print(f"Order for ground_truth_rels` with argsort: {order_ideal}")
                    # idcg_score = dcg(np.take(ground_truth_rels, order_ideal) )

                    # print(f"ideal DCG: {idcg_score}")

    # Let's try to compute score DPS


    # Learning permutation matrics from predicted scores,
    # then apply it to the ground truth to get it sorted based on `predicted` understanding of relevances
    predicted_np = np.array([predicted])
    predicted_tensor = tf.constant(predicted_np, dtype=tf.float32)
    order_soft_P = soft_sort(predicted_tensor, tau=1.0)

    # applying soft permutation matrix
    gr_tr_np = np.array([ground_truth_rels])
    gr_tr_tensor = tf.constant(gr_tr_np, dtype=tf.float32)
    gr_tr_expanded = tf.expand_dims(gr_tr_tensor, axis=2)
    tf.print("gr_tr_tensor", tf.shape(gr_tr_tensor))

    sorted_ground_truth_by_pred = tf.matmul(order_soft_P, gr_tr_expanded) 

    tf.print("Ground truth sorted based on predicted scores:", sorted_ground_truth_by_pred)

    print(sorted_ground_truth_by_pred.numpy().shape)
    sorted_ground_truth_by_pred_np = np.squeeze(sorted_ground_truth_by_pred.numpy())

    dcg_score_pred = dcg(sorted_ground_truth_by_pred_np)
    tf.print("dcg_score_pred:", dcg_score_pred)

    gr_tr_sorted = tf.sort(gr_tr_tensor, direction='DESCENDING', axis=1)

    tf.print("Ground truth sorted directly", gr_tr_sorted)

    print(gr_tr_sorted.numpy().shape)
    gr_tr_sorted_np = np.squeeze(gr_tr_sorted.numpy())

    dcg_score_ideal = dcg(gr_tr_sorted_np)
    tf.print("dcg_score_ideal:", dcg_score_ideal)

    soft_ndsg = dcg_score_pred / dcg_score_ideal
    print(f"Normalized soft DCG: {soft_ndsg}")

    print(f"="*50)

    gt_order_soft_P = soft_sort(gr_tr_tensor, tau=1.0)
    sorted_ground_truth_by_true = tf.matmul(gt_order_soft_P, gr_tr_expanded) 

    tf.print("sorted_ground_truth_by_true:", sorted_ground_truth_by_true)

    true_soft_sorted = np.squeeze(sorted_ground_truth_by_true.numpy())
    pred_soft_sorted = sorted_ground_truth_by_pred_np

    get_combinations((true_soft_sorted, pred_soft_sorted))  # take out def transform_sequence(inputs) in a separate cell if needed


In [40]:
# order = np.argsort(y_pred)[::-1]   takes predicted scores for the same positions as in y_true, so that it basically give the score for each relevance in y_true to induce order
# dcg_score = dcg(np.take(y_true, order))   then take scores for induced ranking and basically sort y_true by scores. 
# note that in training we now labels( relevances) but untimate goal is to only use features of elements to predict scores that will induce ranking



## Benchmarking for the Soft DPRS

Empirical LETOR model comparisons on MSLR-WEB10K, showing LambdaMART best with NDCG@10 around 0.4298.

Dataset:
https://www.microsoft.com/en-us/research/project/mslr/

In [5]:
import keras_rs

# x1 = keras_rs.layers.FeatureCross()(x0, x0)
hinge_loss = keras_rs.losses.PairwiseHingeLoss()
metric = keras_rs.metrics.NDCG(10, name="ndcg")




## Load LETOR files

Dataset: https://www.microsoft.com/en-us/research/project/mslr/

In [6]:
import os

# Path to root folder containing Fold1/, Fold2/, ..., Fold5/
data_dir = "MSLR-WEB10K"


    
def load_letor_file(file_path, num_features=136, max_records=None):
    """
    Reads a LETOR format file into NumPy arrays of X, y, qids.
    If max_records is given, only reads up to that many rows.
    """
    X, y, qids = [], [], []
    with open(file_path, 'r') as f:
        for i, line in enumerate(f):
            if max_records is not None and i >= max_records:
                break
            parts = line.strip().split()
            # First element is relevance label
            y.append(float(parts[0]))
            # Second element is query ID
            qids.append(int(parts[1].split(":")[1]))
            # Remaining elements are "feature:value"
            features = [0.0] * num_features
            for fv in parts[2:]:
                fid, val = fv.split(":")
                features[int(fid) - 1] = float(val)
            X.append(features)

    return (
        np.array(X, dtype=float),
        np.array(y, dtype=float),
        np.array(qids, dtype=int)
    )   

# === Preload all folds ===
folds_data = []  # list of dicts: each dict has keys 'train', 'vali', 'test'

slice_size = 500

for fold_num in range(1, 6):
    fold_name = f"Fold{fold_num}"
    fold_path = os.path.join(data_dir, fold_name)

    # Load train/vali/test once into memory
    train_data = load_letor_file(os.path.join(fold_path, "train.txt"), max_records=slice_size)
    vali_data  = load_letor_file(os.path.join(fold_path, "vali.txt"), max_records=slice_size)
    test_data  = load_letor_file(os.path.join(fold_path, "test.txt"), max_records=None) # let's try to evaluate on all test data at least

    folds_data.append({
        "train": train_data,
        "vali":  vali_data,
        "test":  test_data
    })
    print(f"✅ Loaded {fold_name} folds into memory.")

print(f"✅ Loaded {len(folds_data)} folds into memory.")


✅ Loaded Fold1 folds into memory.
✅ Loaded Fold2 folds into memory.
✅ Loaded Fold3 folds into memory.
✅ Loaded Fold4 folds into memory.
✅ Loaded Fold5 folds into memory.
✅ Loaded 5 folds into memory.


In [17]:
print(folds_data[0]["train"][0].shape)
print(folds_data[0]["test"][0].shape)

(500, 136)
(241521, 136)


## Earlystopping callbacks

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Define a learning rate schedule function (step decay example)
def lr_schedule(epoch, lr):
    drop_rate = 0.5
    epochs_drop = 10
    if epoch > 0 and epoch % epochs_drop == 0:
        return lr * drop_rate
    return lr

#Instantiate callback
lr_scheduler = tf.keras.callbacks.LearningRateScheduler(lr_schedule)

# Or adaptive reduction on plateau (reduce LR when val_loss stalls)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-6)


from tensorflow.keras.callbacks import CSVLogger

# csv_logger = CSVLogger('training_log.csv', append=True)

es_callbacks=[lr_scheduler, reduce_lr, early_stop] # csv_logger

## Reshape inputs for the model 

In [8]:

import numpy as np
import tensorflow as tf

def group_by_query_id(X_docs, y_docs, qids_docs, debug=False):
    # Convert to NumPy if inputs are not already
    qids = np.asarray(qids_docs)
    X = np.asarray(X_docs)
    y = np.asarray(y_docs)
    
    if debug:
        print("Original X:\n", X)
        print("Original shape:", X.shape)
        print("Original qids:", qids)

    # 1. Find unique query IDs and mapping from doc index to query index
    unique_qids, inverse_indices = np.unique(qids, return_inverse=True)
    num_unique_queries = len(unique_qids)

    # 2. Group documents & labels for each unique query into Python lists
    docs_grouped = []
    labels_grouped = []
    for q in range(num_unique_queries):
        mask = inverse_indices == q
        docs_grouped.append(X[mask])     # shape (docs_for_query, num_features)
        labels_grouped.append(y[mask])  # shape (docs_for_query,)

    # 3. Convert each group into one RaggedTensor (no padding!)
    docs_ragged = tf.ragged.constant(docs_grouped, ragged_rank=1)   # shape: [num_queries, (variable_docs), num_features]
    labels_ragged = tf.ragged.constant(labels_grouped, ragged_rank=1)  # shape: [num_queries, (variable_docs)]

    unique_qids_ragged = tf.ragged.constant(unique_qids, ragged_rank=0)
    if debug:
        print("Ragged docs shape:", docs_ragged.bounding_shape())
        print("Example row lens:", docs_ragged.row_lengths().numpy())
        print("Ragged labels:", labels_ragged)

    return docs_ragged.to_tensor(), labels_ragged.to_tensor(), unique_qids_ragged
    


In [68]:
# def group_by_query_id(X_docs, y_docs, qids_docs, debug=False):
#     return group_by_query_id_ragged(X_docs, y_docs, qids_docs, debug)

In [9]:
# Example data
qids = np.array([1, 1, 2, 2, 2, 3])
X = np.arange(len(qids) * 4).reshape(len(qids), 4)
y = np.array([1, 0, 1, 1, 0, 1])

docs_ragged, labels_ragged, uqids = group_by_query_id(X, y, qids, debug=True)

print("\nDocs RaggedTensor:", docs_ragged)
print("\nDocs RaggedTensor.shape:", docs_ragged.shape)
print("Labels RaggedTensor:", labels_ragged)
print("uqids :", uqids)
uqids

Original X:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Original shape: (6, 4)
Original qids: [1 1 2 2 2 3]
Ragged docs shape: tf.Tensor([3 3 4], shape=(3,), dtype=int64)
Example row lens: [2 3 1]
Ragged labels: <tf.RaggedTensor [[1, 0], [1, 1, 0], [1]]>

Docs RaggedTensor: tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 0  0  0  0]]

 [[ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [ 0  0  0  0]
  [ 0  0  0  0]]], shape=(3, 3, 4), dtype=int32)

Docs RaggedTensor.shape: (3, 3, 4)
Labels RaggedTensor: tf.Tensor(
[[1 0 0]
 [1 1 0]
 [1 0 0]], shape=(3, 3), dtype=int32)
uqids : tf.Tensor([1 2 3], shape=(3,), dtype=int64)


<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

## Evaluate avg. hyperparameters performance

In [10]:
def evaluate_avg_hps_performance(all_best_hps, X_trainval, y_trainval, qids_trainval, max_docs):
    avg_hps_losses = []

    for hp, loss in all_best_hps:
        print(f"HPS: {hp.values}. Loss during RandomSearch: {loss}. Starting evaluation across all k folds...")
        model = tuner.hypermodel.build(hp)
        
        cv_loss_scores = []
        
        n_splits = 5
        gkf = GroupKFold(n_splits=n_splits)
        

        # Iterate over grouped folds
        for fold_idx, (train_idx, val_idx) in enumerate(gkf.split(X_trainval, y_trainval, groups=qids_trainval), start=1):
            
            train_item_ids, train_labels, train_user_ids  = group_by_query_id(
                X_trainval[train_idx],
                y_trainval[train_idx],
                qids_trainval[train_idx]
            )

            val_item_ids, val_labels, val_user_ids = group_by_query_id(
                X_trainval[val_idx],
                y_trainval[val_idx],
                qids_trainval[val_idx]
            )
            
            train_x = {
                "user_id": train_user_ids,
                'doc_features': train_item_ids
            }
            val_x = {
                "user_id": val_user_ids,
                "doc_features": val_item_ids
            }
            
            history = model.fit(train_x, train_labels, validation_data=(val_x, val_labels), epochs=50)
            # Access training and validation loss per epoch
            # train_loss = history.history['loss'][-1]
            val_loss = history.history['val_loss'][-1]
            cv_loss_scores.append(val_loss)
        
        print(f"Validation losses: {cv_loss_scores}")
        avg_cv_loss =  sum(cv_loss_scores) / len(cv_loss_scores)   
        
        avg_hps_losses.append((hp, avg_cv_loss))
    
    return avg_hps_losses

## Selecting best avg. hps

In [11]:
def selecting_best_avg_hps(avg_hps_losses):
    best_avg_hp = None
    best_avg_hp_val_score = -np.inf
    for hp, avg in avg_hps_losses:
        print(f"HPS: {hp.values} Avg. across folds score(MSE): {avg}")
        if avg > best_avg_hp_val_score:
            best_avg_hp_val_score = avg
            best_avg_hp = hp
    return best_avg_hp, best_avg_hp_val_score

## Train model on all data for best avg. hyperparameters

In [12]:
def train_best_hps_model(best_hps, X_trainval, y_trainval, qids_trainval, max_docs):
    
    avg_hps_losses = evaluate_avg_hps_performance(best_hps, X_trainval, y_trainval, qids_trainval, max_docs)
    
    best_avg_hp, best_avg_hp_val_score = selecting_best_avg_hps(avg_hps_losses)
    
    print(f"HPS: {best_avg_hp.values}. Avg loss: {best_avg_hp_val_score}.")
    
    model_hp = tuner.hypermodel.build(best_avg_hp)
    

    train_item_ids, train_labels, train_user_ids  = group_by_query_id(
            X_trainval,
            y_trainval,
            qids_trainval
        )
    
    train_x = {
            "user_id": train_user_ids,
            'doc_features': train_item_ids
        }


    history = model_hp.fit(train_x, train_labels, epochs=50)
    train_loss = history.history['loss'][-1]
    
    return model_hp, train_loss

## Start the the model training. Data preparation and training

In [58]:
gpus = tf.config.list_physical_devices('GPU')
print("GPUs found:", gpus)

GPUs found: []


In [59]:
tf.debugging.set_log_device_placement(True)

In [63]:
from sklearn.model_selection import GroupKFold

all_k_models_and_test_folds = []

for fold_idx, fold_data in enumerate(folds_data[:1], start=1):
    (X_train, y_train, qids_train) = fold_data["train"]
    (X_val,   y_val,   qids_val)   = fold_data["vali"]
    (X_test,  y_test,  qids_test)  = fold_data["test"]

    print(f"\n=== Fold {fold_idx} ===")
    print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

    # Train your model here, using the arrays above
    # e.g.: model.fit(X_train, y_train)
    X_trainval   = np.concatenate([X_train, X_val], axis=0)
    y_trainval   = np.concatenate([y_train, y_val], axis=0)
    qids_trainval   = np.concatenate([qids_train, qids_val], axis=0)
    
    # Combine all splits to consider full fold
    combined_qids = np.concatenate([qids_train, qids_val, qids_test])

    from collections import Counter
    doc_counts = Counter(combined_qids)
    max_docs = max(doc_counts.values())

    print(f"Max documents per query in this fold: {max_docs}")
    
    
    # Choose number of folds for *internal* CV
    n_splits = 5
    gkf = GroupKFold(n_splits=n_splits)
    
    max_trials = 5
    
    best_val_score = -np.inf
    best_hps = None

    all_best_hps = []

    # Iterate over grouped folds ( data is train and valid concatenated)
    for sub_fold_idx, (train_idx, val_idx) in enumerate(gkf.split(X_trainval, y_trainval, groups=qids_trainval), start=1):
        
        print(f'\nFOLD {sub_fold_idx}')
        tuner = kt.RandomSearch(
            hypermodel,
            objective=kt.Objective('val_loss', direction='min'),
            max_trials=max_trials,
            executions_per_trial=1,
            overwrite=True,
            directory='ktuner_dir',
            project_name=f'fletor_fold_{sub_fold_idx}'
        )
        
        
        #  =  # user id is a query id
        train_item_ids, train_labels, train_user_ids  = group_by_query_id(
            X_trainval[train_idx],
            y_trainval[train_idx],
            qids_trainval[train_idx]
        )
        print("train_user_ids shape:", train_user_ids.shape)
        print("train_item_ids shape:", train_item_ids.shape)
        print("train_labels shape:", train_labels.shape)
        
        #  =  # user id is a query id
        val_item_ids, val_labels, val_user_ids = group_by_query_id(
            X_trainval[val_idx],
            y_trainval[val_idx],
            qids_trainval[val_idx]
        )
        
        # Create dict input exactly like your model expects
        train_x = {
            "user_id": train_user_ids,
            'doc_features': train_item_ids
        }
        val_x = {
            "user_id": val_user_ids,
            "doc_features": val_item_ids
        }
        
        tuner.search(
            train_x, train_labels,
            validation_data=(val_x, val_labels),
            epochs=50,
            batch_size=16,
            callbacks = es_callbacks, 
            verbose=1
        )
        
        # raise ValueError("Stop for now")
        

        best_trial = tuner.get_best_hyperparameters(1)[0]
        # best_model = tuner.get_best_models(1)[0]
        best_model = hypermodel.build(best_trial)
        # best_model = RankingModel(
        #     num_users=NUM_USERS,
        #     num_items=NUM_ITEMS,
        #     embedding_dim=EMBEDDING_DIM,
        #     hp=best_trial
        # )
        # best_model.compile(
        #     optimizer=keras.optimizers.Adagrad(
        #         learning_rate=0.01
        #     ),
        #     loss=custom_loss,
        #     metrics=[]  # add your metrics here
        # )
        
        eval_results = best_model.evaluate(val_x, val_labels, verbose=1)
        
        print(f"1: {eval_results}  ")
        val_acc = eval_results
        
        
        all_best_hps.append((best_trial, val_acc))
        
        print(val_acc)
        # print(f"Fold {fold+1} best val MSE: {val_acc:.4f}")

        if val_acc > best_val_score:
            best_val_score = val_acc
            best_hps = best_trial
            
            
    print(f"\nBest single hyperparameters found (fold={fold_idx}):")
    for hp in best_hps.values.keys():
        print(f"{hp}: {best_hps.get(hp)}")
        
    print(f"FOlD={fold_idx}. Instead of using single hyperparameters found, we will take best from every GroupKFold split and estimate them on average")
    model_hp, model_hp_test_loss = train_best_hps_model(all_best_hps, X_trainval, y_trainval, qids_trainval, max_docs)  
    
    all_k_models_and_test_folds.append((model_hp, fold_data["test"]))
    


Trial 5 Complete [00h 00m 06s]
val_loss: 1.2677714824676514

Best val_loss So Far: 1.2154462337493896
Total elapsed time: 00h 00m 32s
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 371ms/step - loss: 1.6929
1: 1.6928894519805908  
1.6928894519805908

Best single hyperparameters found (fold=1):
dense_units: 48
dense_units_2: 96
dropout_rate: 0.4
dropout_rate_2: 0.2
attention_heads: 4
attention_dropout_rate: 0.30000000000000004
learning_rate: 0.05
FOlD=1. Instead of using single hyperparameters found, we will take best from every GroupKFold split and estimate them on average
HPS: {'dense_units': 64, 'dense_units_2': 96, 'dropout_rate': 0.2, 'dropout_rate_2': 0.1, 'attention_heads': 4, 'attention_dropout_rate': 0.30000000000000004, 'learning_rate': 0.05}. Loss during RandomSearch: 1.3797922134399414. Starting evaluation across all k folds...
Epoch 1/50


/opt/anaconda3/envs/graph_temporal/lib/python3.12/site-packages/keras/src/layers/layer.py:965: UserWarning: Layer 'self_attenction_block_1' (of type SelfAttentionBlock) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 1.7956 - val_loss: 1.5720
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 2.3761 - val_loss: 2.8342
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 3.8157 - val_loss: 3.8739
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 4.9026 - val_loss: 1.8706
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 2.4732 - val_loss: 1.1994
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1.1590 - val_loss: 1.0535
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.0883 - val_loss: 1.2030
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.1460 - val_loss: 1.1069
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.0936 - val_loss: 1.0544
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.0657 - val_loss: 1.1766
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.1134 - val_loss: 1.1115
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.0732 - val_loss: 1.0547
Epoch 13/50
1/

/opt/anaconda3/envs/graph_temporal/lib/python3.12/site-packages/keras/src/layers/layer.py:965: UserWarning: Layer 'self_attenction_block_1' (of type SelfAttentionBlock) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 1.2412 - val_loss: 2.7383
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.4895 - val_loss: 1.7150
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.5838 - val_loss: 5.3870
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 7.6384 - val_loss: 1.8314
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.6072 - val_loss: 1.5425
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.7421 - val_loss: 1.3709
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.2509 - val_loss: 1.2786
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 1.5189 - val_loss: 1.1670
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 1.1246 - val_loss: 1.1298
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 1.1039 - val_loss: 1.2385
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.1456 - val_loss: 1.0921
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.0770 - val_loss: 1.1037
Epoch 13/50
1

/opt/anaconda3/envs/graph_temporal/lib/python3.12/site-packages/keras/src/layers/layer.py:965: UserWarning: Layer 'self_attenction_block_1' (of type SelfAttentionBlock) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 1.3284 - val_loss: 2.5783
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2.1339 - val_loss: 2.2525
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.8740 - val_loss: 4.0031
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 5.5553 - val_loss: 1.2702
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 1.1544 - val_loss: 1.4159
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.4316 - val_loss: 1.6128
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 1.5805 - val_loss: 1.1305
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1.0847 - val_loss: 1.1408
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.0839 - val_loss: 1.2175
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.1035 - val_loss: 1.1494
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.0641 - val_loss: 1.1674
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.0620 - val_loss: 1.2297
Epoch 13/50
1/

/opt/anaconda3/envs/graph_temporal/lib/python3.12/site-packages/keras/src/layers/layer.py:965: UserWarning: Layer 'self_attenction_block_1' (of type SelfAttentionBlock) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 1.2273 - val_loss: 1.4284
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1.9850 - val_loss: 1.3961
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1.5077 - val_loss: 1.8021
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1.7882 - val_loss: 1.9922
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 2.3223 - val_loss: 4.2845
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 5.5983 - val_loss: 1.5247
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1.4226 - val_loss: 2.2957
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 3.0106 - val_loss: 1.4200
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1.2540 - val_loss: 1.0608
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1.0868 - val_loss: 1.2016
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1.1382 - val_loss: 1.1212
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1.0997 - val_loss: 1.0842
Epoch 13/50
1/

/opt/anaconda3/envs/graph_temporal/lib/python3.12/site-packages/keras/src/layers/layer.py:965: UserWarning: Layer 'self_attenction_block_1' (of type SelfAttentionBlock) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 2.0434 - val_loss: 2.9940
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 3.2849 - val_loss: 1.2989
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.5935 - val_loss: 13.0658
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 19.7706 - val_loss: 4.6114
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 6.8457 - val_loss: 2.1823
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 2.3119 - val_loss: 3.1097
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 4.3913 - val_loss: 1.5625
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.5142 - val_loss: 1.1359
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.2550 - val_loss: 1.1160
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.1257 - val_loss: 1.0562
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.0913 - val_loss: 1.0389
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.0809 - val_loss: 1.0269
Epoch 13/50


## Evaluation v1

In [32]:

ndcg_all_results = []

for model_fold, test_fold_data in all_k_models_and_test_folds:
    
    
    (X_test,  y_test,  qids_test)  = test_fold_data
    print(f"X_test.shape", X_test.shape)
    print(f"y_test.shape", y_test.shape)
    print(f"qids_test.shape", qids_test.shape)

    test_item_ids, test_labels, test_user_ids  = group_by_query_id(
            X_test,
            y_test,
            qids_test,
    )
    
    test_x = {
            "user_id": test_user_ids,
            'doc_features': test_item_ids
        }

    # Get the predicted scores per item
    predicted_scores = model_fold.predict(test_x, batch_size=50)  # batch_size matches input batch size
    print(predicted_scores) 
    
    ndcg_metric = keras_rs.metrics.NDCG(k=10, name="ndcg")

    # Convert predictions and true labels to tensors if needed
    y_true = test_labels     # shape: (batch_size, list_size)
    y_pred = predicted_scores  # same shape
    print(f"test_labels.shape", test_labels.shape)
    print(f"predicted_scores.shape", predicted_scores.shape)

    # Reset internal state before updating metric
    ndcg_metric.reset_state()

    # Update metric with current batch
    ndcg_metric.update_state(y_true, y_pred)
    print(f"y_true.shape", y_true.shape)

    # Get the evaluated result (scalar tensor)
    ndcg_result = ndcg_metric.result().numpy()

    print(f"Fold {fold_idx} is completed. NDCG@10: {ndcg_result}")
    ndcg_all_results.append(ndcg_result)
    
print(f"All NDCGs: {ndcg_all_results}")
avg_ndcg =  sum(ndcg_all_results) / len(ndcg_all_results)  
print(f"Average NDCG: {avg_ndcg}") 

X_test.shape (241521, 136)
y_test.shape (241521,)
qids_test.shape (241521,)
Shape of the doc_features (50, 514, 136)
Shape of the mask (50, 514)
Shape of the mask_expanded (50, 1, 514)
 1/40 ━━━━━━━━━━━━━━━━━━━━ 9s 238ms/step

/opt/anaconda3/envs/graph_temporal/lib/python3.12/site-packages/keras/src/layers/layer.py:965: UserWarning: Layer 'self_attenction_block_1' (of type SelfAttentionBlock) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask.
  warnings.warn(


40/40 ━━━━━━━━━━━━━━━━━━━━ 5s 113ms/step
[[0.00909737 0.00909737 0.00909737 ... 0.00801841 0.00801841 0.00801841]
 [0.00909737 0.02877014 0.00909737 ... 0.00801841 0.00801841 0.00801841]
 [0.00909737 0.02392443 0.02114697 ... 0.00801841 0.00801841 0.00801841]
 ...
 [0.03370776 0.02564774 0.03384894 ... 0.00801841 0.00801841 0.00801841]
 [0.02461334 0.02709259 0.00909737 ... 0.00801841 0.00801841 0.00801841]
 [0.00909737 0.00909737 0.00909737 ... 0.00801841 0.00801841 0.00801841]]
test_labels.shape (2000, 514)
predicted_scores.shape (2000, 514)
y_true.shape (2000, 514)
Fold 2 is completed. NDCG@10: 0.1948341727256775
X_test.shape (241988, 136)
y_test.shape (241988,)
qids_test.shape (241988,)
Shape of the doc_features (50, 809, 136)
Shape of the mask (50, 809)
Shape of the mask_expanded (50, 1, 809)
40/40 ━━━━━━━━━━━━━━━━━━━━ 7s 176ms/step
[[ 0.01248189  0.0124828   0.0113681  ... -0.14779533 -0.14779533
  -0.14779533]
 [ 0.01240618  0.01240855  0.01240998 ... -0.14779533 -0.14779533
  -

In [82]:
all_k_models_and_test_folds[0][1][0].shape

(241521, 136)

It is indeed unusual for classic k-fold cross-validation to include three splits (train, validation, and test) per fold. The standard purpose of k-fold cross-validation is to estimate model generalization by:

Splitting data into K folds.

For each run, using K−1 folds as training, and 1 fold for validation (often called "test" fold in this context).

Repeating until each fold has acted as the validation fold, then averaging results.

There is no separate "test" fold in classical k-fold CV—the entire dataset is used for both training and validation across the K iterations, maximizing data use for model selection and evaluation.

## Training time considerations and optimization

### Slicing

For the first iterations only a portion of data was used. Experiments with 1K and 20K slices showed that running on a whole dataset would not be feasible on a laptop setup:
- 1K per fold training time was around ~60 minutes on MacBook Air
- 20K per fold training time was around 10hours 

Slicing obviously only suitable for initial iterations of model building and of course nobody wants to give up on using all the data for training.

Note that this drastic degradation of performance might be related to an efficient custom loss fucntion implementation. That is just another opportunity to experiment and learn. We can compare performance between NDCG and DPRS

### RaggedTensors and Masking for padded data

Because current implementation doesn't cap number of documents per query we probably have lots of padded values in our data. This is one of the directions for optimisation. We need to make sure that masking is applied and we can experiment with RaggedTensors that are designed for variable-length sequences.

### Training on GPU or TPU 

Leveraging highly parallelizable computing units like GPU or TPU is a common solution when training times need to be improved. 
Options:
- TPU is designed by Google and only available on GCP platform
- GPUs are less optimized for tensor floating number computations but still outperform CPUs by 5+ times

For the same of the education I'm going to start with AWS Sagemaker AI notebook with single GPU instances and estimate training time improvement.

Is it correct as Dense layers never support raggedTensors and because we always have Dense layers at the end of the model means we never need to transform labels to a ragged format

Answer:
Dense layers in TensorFlow/Keras generally do NOT support ragged tensors as inputs directly. They expect dense tf.Tensor with fixed shapes.

Because of this, when using ragged inputs, you usually need to convert ragged tensors to padded dense tensors before passing them to dense layers, via .to_tensor() or equivalent.

Most models end with Dense layers (e.g., for scoring or classification), so these layers require fixed-size inputs.

This means your labels (targets) also typically do not need to be ragged tensors because the loss computation expects predictions and labels with matching fixed shapes for elementwise comparison.

If labels had ragged structure, you'd have to ensure they are compatible with model outputs and loss computation, which is uncommon especially when the model outputs dense tensors.

## Comparing implemented DPRS metric's performance with performance of existing metrics 

In [198]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
import tensorflow_ranking as tfr
# approx_ndcg = tfr.keras.losses.ApproxNDCGLoss()



ImportError: cannot import name 'estimator' from 'tensorflow' (/opt/anaconda3/envs/graph_temporal/lib/python3.12/site-packages/tensorflow/__init__.py)

In [204]:
listMLE = tfr.keras.losses.ListMLELoss()

NameError: name 'tfr' is not defined

## Masking

### Does masking improve performance of the keras model training?

Masking in Keras helps improve model performance primarily by **allowing layers to ignore padded timesteps** during processing and training. This avoids wasting computation and incorrect gradient updates on padded data, leading to more efficient and sometimes more accurate training.

### How masking improves performance:

- **Efficiency**: Layers like RNNs, LSTMs, or attention layers skip operations on padded tokens, reducing unnecessary computation.
- **Correctness**: Loss and metrics calculations exclude padded data, reducing noise and potential bias from padded values.
- **Memory**: Masking avoids the overhead of considering padded elements in backpropagation and gradient updates.


### Compared to ragged tensors:

- Keras supports masking with `Embedding(mask_zero=True)` or `Masking` layers and propagates masks automatically through compatible layers.
- Ragged tensors represent variable-length sequences without padding.
- Recent TensorFlow versions handle masks and ragged tensors similarly in terms of loss and metrics, yielding identical loss values when masks are respected.[^1][^5]
- However, ragged tensors usually require additional conversion (`to_tensor()`) to work with some Keras layers, which may add overhead.


### Practical impact on training speed:

- Masking typically **improves training speed** by skipping padded elements.
- Performance gain depends on the quantity of padding relative to actual data.
- If there's little padding, speedup might be minimal.
- Speed improvements come from less computation and often better utilization of GPU/CPU.




#### Introduced Masking layer and applied it before first layer ( attention layer in our case)

```
self.masked = layers.Masking(mask_value=0.0)
...
x = self.masked(doc_features) 
x = self.attn_self(x )
````

Important note, when you are using Subclassin API ( not Sequence or Functional APIs) we don't need to use layers.Input as `call(self, inputs)` will already have the exact inputs you pass to the model. So basically we have to handle types of inputs in that case outside of the model.

## Ragged Tensors

The benefits of ragged tensors in TensorFlow are primarily related to their ability to efficiently represent and manipulate data with variable-length dimensions without padding, making them highly useful for many real-world data scenarios:

- Support variable-length sequences: Ragged tensors naturally handle data where elements along one dimension have different lengths, such as sentences of varying word counts, time series of different durations, or nested lists. This avoids the need for padding sequences to a fixed length, saving memory and computation.

- Efficient storage and computation: Unlike padded dense tensors, ragged tensors store only the actual values and metadata about row splits, eliminating wasted space due to padding. This can improve both memory efficiency and speed, especially with large datasets of uneven length.

- Native support in TensorFlow ops: More than a hundred TensorFlow operations support ragged tensors, including math operations (e.g., addition, mean), array manipulations (concatenation, tiling), string processing, and control flow. This allows seamless integration into models and data pipelines without manual padding or masking.

- Better representation of hierarchical or nested data: Ragged tensors can represent complex data structures like documents subdivided into paragraphs and sentences, or sequences of sequences, which are common in NLP, speech, and other domains.

- Facilitate training with variable batch elements: With ragged tensors, models like RNNs or transformers can process input batches with variable-length sequences more naturally, improving flexibility and potentially reducing preprocessing complexity.

#### Small example of the usage

In [200]:
import tensorflow as tf

ragged1 = tf.ragged.constant([[1, 2], [3]])
ragged2 = tf.ragged.constant([[4, 5], [6]])

# Element-wise addition (requires compatible shapes)
added = tf.add(ragged1, ragged2)
print("Added RaggedTensor:", added)

# Concatenate along axis 0 (rows)
concat = tf.concat([ragged1, ragged2], axis=0)
print("Concatenated RaggedTensor:", concat)

# Compute mean values in each row
print(ragged1.shape)
mean_values = tf.reduce_mean(ragged1, axis=1)
print("Mean per row:", mean_values.numpy())

Added RaggedTensor: <tf.RaggedTensor [[5, 7], [9]]>
Concatenated RaggedTensor: <tf.RaggedTensor [[1, 2], [3], [4, 5], [6]]>
(2, None)
Mean per row: [1.5 3. ]


```{seealso}
Jupyter Book uses [Jupytext](https://jupytext.readthedocs.io/en/latest/) to convert text-based files to notebooks, and can support [many other text-based notebook files](https://jupyterbook.org/file-types/jupytext.html).
```

## Soft sort

In [45]:
import tensorflow as tf

def soft_sort(s, tau=1.0):
    """
    s: Tensor of shape [batch_size, n] with scores to sort
    tau: temperature parameter (lower -> closer to hard argsort)
    returns: soft permutation matrices of shape [batch_size, n, n]
    """
    s = tf.cast(s, tf.float32)
    batch_size = tf.shape(s)[0]
    n = tf.shape(s)[1]

    # Sort scores descending along axis 1 for target sorted positions
    s_sorted = tf.sort(s, direction='DESCENDING', axis=1)

    # Expand dims for pairwise distance computation
    # s shape becomes [batch_size, 1, n]
    s_exp1 = tf.expand_dims(s, axis=1)
    # s_sorted shape becomes [batch_size, n, 1]
    s_exp2 = tf.expand_dims(s_sorted, axis=2)

    # Compute negative absolute distances for soft matching: 
    # shape: [batch_size, n, n]
    pairwise_distances = -tf.abs(s_exp1 - s_exp2)

    # Apply softmax over last axis with temperature tau
    P = tf.nn.softmax(pairwise_distances / tau, axis=-1)

    return P  # soft permutation matrix approximating argsort


## DCG & NDCG

In [89]:
def dcg(relevances):
    """
    Compute Discounted Cumulative Gain (DCG)
    relevances: list or numpy array of relevance scores in predicted order
    """
    relevances = np.asarray(relevances)
    discounts = np.log2(np.arange(2, len(relevances) + 2))
    return np.sum(relevances / discounts)

def ndcg(y_true, y_pred, k=None):
    """
    Compute Normalized DCG (NDCG) for a single query
    y_true: true relevance scores (same order as items)
    y_pred: predicted scores from model
    k: cutoff rank (optional), only top-k positions are considered
    """
    # Rank items by predicted scores
    order = np.argsort(y_pred)[::-1]
    if k:
        order = order[:k]

    print(f"Predicted order: {order}")
    # DCG using predicted order
    dcg_score = dcg(np.take(y_true, order))

    # Ideal DCG (best possible order)
    ideal_order = np.argsort(y_true)[::-1]
    if k:
        ideal_order = ideal_order[:k]
    idcg_score = dcg(np.take(y_true, ideal_order))

    return dcg_score / idcg_score if idcg_score > 0 else 0.0


# ---- Example data ----
y_true = np.array([3, 2, 3, 0, 1])        # true relevance labels
y_pred = np.array([0.4, 0.7, 0.2, 0.1, 0.8])  # model-predicted scores

# print("DCG:", dcg(y_true))
print("NDCG:", ndcg(y_true, y_pred))
# print("NDCG@3:", ndcg(y_true, y_pred, k=3))

Predicted order: [4 1 0 2 3]
NDCG: 0.7992277219792019
